export const sampleCollections = [
  {
    id: 'col_sample1',
    name: 'Morgan Silver Dollars',
    description: 'Complete type set of Morgan dollars spanning the classic era',
    type: 'By Series',
    targetGoal: 'Complete Morgan Dollar set 1878-1921',
    coverImage: null,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-03-10T14:30:00Z',
  },
  {
    id: 'col_sample2',
    name: 'World Gold Coins',
    description: 'Sovereigns, Eagles, and rare world gold coinage',
    type: 'By Metal',
    targetGoal: '',
    coverImage: null,
    createdAt: '2024-02-20T09:00:00Z',
    updatedAt: '2024-03-12T11:00:00Z',
  },
];

export const sampleCoins = [
  {
    id: 'coin_sample1',
    collectionId: 'col_sample1',
    country: '🇺🇸 United States',
    denomination: 'Morgan Dollar',
    year: '1921',
    mintMark: 'D',
    series: 'Morgan Silver Dollar',
    composition: 'Silver',
    diameter: '38.1',
    weight: '26.73',
    userGrade: 'MS-63',
    purchasePrice: '85',
    purchaseDate: '2024-01-20',
    whereAcquired: 'Dealer',
    conditionNotes: 'Bright luster, minor contact marks',
    personalNotes: 'Beautiful coin, great eye appeal',
    storageLocation: '2x2 flip, Box 1, Slot 3',
    tags: ['type coin', 'silver'],
    obverseImage: null,
    reverseImage: null,
    aiGrade: null,
    enrichment: null,
    marketValue: null,
    createdAt: '2024-01-20T12:00:00Z',
    updatedAt: '2024-01-20T12:00:00Z',
  },
  {
    id: 'coin_sample2',
    collectionId: 'col_sample1',
    country: '🇺🇸 United States',
    denomination: 'Morgan Dollar',
    year: '1884',
    mintMark: 'O',
    series: 'Morgan Silver Dollar',
    composition: 'Silver',
    diameter: '38.1',
    weight: '26.73',
    userGrade: 'AU-55',
    purchasePrice: '55',
    purchaseDate: '2024-02-14',
    whereAcquired: 'Auction',
    conditionNotes: 'Light wear on high points',
    personalNotes: 'Nice original surfaces',
    storageLocation: '2x2 flip, Box 1, Slot 4',
    tags: ['original surfaces'],
    obverseImage: null,
    reverseImage: null,
    aiGrade: null,
    enrichment: null,
    marketValue: null,
    createdAt: '2024-02-14T15:00:00Z',
    updatedAt: '2024-02-14T15:00:00Z',
  },
];

export const SHELDON_GRADES = [
  { grade: 'P-1', name: 'Poor', category: 'circulated' },
  { grade: 'F-2', name: 'Fair', category: 'circulated' },
  { grade: 'AG-3', name: 'About Good', category: 'circulated' },
  { grade: 'G-4', name: 'Good', category: 'circulated' },
  { grade: 'G-6', name: 'Good', category: 'circulated' },
  { grade: 'VG-8', name: 'Very Good', category: 'circulated' },
  { grade: 'VG-10', name: 'Very Good', category: 'circulated' },
  { grade: 'F-12', name: 'Fine', category: 'circulated' },
  { grade: 'F-15', name: 'Fine', category: 'circulated' },
  { grade: 'VF-20', name: 'Very Fine', category: 'circulated' },
  { grade: 'VF-25', name: 'Very Fine', category: 'circulated' },
  { grade: 'VF-30', name: 'Very Fine', category: 'circulated' },
  { grade: 'VF-35', name: 'Very Fine', category: 'circulated' },
  { grade: 'EF-40', name: 'Extremely Fine', category: 'circulated' },
  { grade: 'EF-45', name: 'Extremely Fine', category: 'circulated' },
  { grade: 'AU-50', name: 'About Uncirculated', category: 'circulated' },
  { grade: 'AU-53', name: 'About Uncirculated', category: 'circulated' },
  { grade: 'AU-55', name: 'About Uncirculated', category: 'circulated' },
  { grade: 'AU-58', name: 'About Uncirculated', category: 'circulated' },
  { grade: 'MS-60', name: 'Mint State', category: 'uncirculated' },
  { grade: 'MS-61', name: 'Mint State', category: 'uncirculated' },
  { grade: 'MS-62', name: 'Mint State', category: 'uncirculated' },
  { grade: 'MS-63', name: 'Choice Uncirculated', category: 'uncirculated' },
  { grade: 'MS-64', name: 'Choice Uncirculated', category: 'uncirculated' },
  { grade: 'MS-65', name: 'Gem Uncirculated', category: 'uncirculated' },
  { grade: 'MS-66', name: 'Gem Uncirculated', category: 'uncirculated' },
  { grade: 'MS-67', name: 'Superb Gem', category: 'uncirculated' },
  { grade: 'MS-68', name: 'Superb Gem', category: 'uncirculated' },
  { grade: 'MS-69', name: 'Superb Gem', category: 'uncirculated' },
  { grade: 'MS-70', name: 'Perfect Uncirculated', category: 'uncirculated' },
  { grade: 'PF-60', name: 'Proof', category: 'proof' },
  { grade: 'PF-63', name: 'Choice Proof', category: 'proof' },
  { grade: 'PF-65', name: 'Gem Proof', category: 'proof' },
  { grade: 'PF-67', name: 'Superb Gem Proof', category: 'proof' },
  { grade: 'PF-69', name: 'Near Perfect Proof', category: 'proof' },
  { grade: 'PF-70', name: 'Perfect Proof', category: 'proof' },
];

export const COUNTRIES = [
  '🇺🇸 United States', '🇬🇧 United Kingdom', '🇨🇦 Canada', '🇦🇺 Australia',
  '🇩🇪 Germany', '🇫🇷 France', '🇮🇹 Italy', '🇪🇸 Spain', '🇳🇱 Netherlands',
  '🇧🇪 Belgium', '🇨🇭 Switzerland', '🇦🇹 Austria', '🇲🇽 Mexico', '🇧🇷 Brazil',
  '🇦🇷 Argentina', '🇷🇺 Russia', '🇨🇳 China', '🇯🇵 Japan', '🇮🇳 India',
  '🇿🇦 South Africa', '🇮🇱 Israel', '🇹🇷 Turkey', '🇬🇷 Greece', '🇸🇪 Sweden',
  '🇳🇴 Norway', '🇩🇰 Denmark', '🇵🇹 Portugal', '🇵🇱 Poland', '🇨🇿 Czech Republic',
  '🇭🇺 Hungary', '🇷🇴 Romania', '🇧🇬 Bulgaria', '🇸🇰 Slovakia', '🇭🇷 Croatia',
  '🇸🇮 Slovenia', '🇸🇬 Singapore', '🇭🇰 Hong Kong', '🇰🇷 South Korea',
  '🇹🇭 Thailand', '🇲🇾 Malaysia', '🇮🇩 Indonesia', '🇵🇭 Philippines',
  '🇳🇿 New Zealand', '🇮🇪 Ireland', '🇫🇮 Finland', '🇱🇺 Luxembourg',
  '🇲🇹 Malta', '🇨🇾 Cyprus', '🇪🇪 Estonia', '🇱🇻 Latvia', '🇱🇹 Lithuania',
  '🏛️ Ancient Rome', '🏛️ Ancient Greece', '🏛️ Byzantine Empire', '⚜️ Other',
];

export const MINT_MARKS = ['None', 'P', 'D', 'S', 'O', 'CC', 'W', 'MM', 'C', 'Custom...'];
export const COMPOSITIONS = ['Copper', 'Silver', 'Gold', 'Nickel', 'Clad', 'Bronze', 'Platinum', 'Palladium', 'Zinc', 'Steel', 'Custom...'];
export const COLLECTION_TYPES = ['By Country', 'By Type', 'By Era', 'By Series', 'By Metal', 'Custom'];
export const ACQUISITION_SOURCES = ['Dealer', 'Auction', 'Inheritance', 'Found in Circulation', 'Trade', 'Online', 'Estate Sale', 'Coin Show', 'Other'];